os:
  - linux

language:
  - python
  
python:
  - 3.6

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check --diff --exclude showup/migrations/* .
  - flake8 .
  - coverage run --source=mysite,showup manage.py test

after_script:
  - coveralls