language: python

install:
    - pip install -r requirements.txt

before_script:
    - python manage.py migrate
    - python manage.py collectstatic --noinput

script:
    - black --check --diff .
    - flake8 .
    - coverage run --source=mysite,showup manage.py test

after_script:
    - coveralls
