# Generated by Django 2.2.5 on 2019-10-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersignup', '0002_loginuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='password',
            field=models.CharField(default=123456, max_length=30),
            preserve_default=False,
        ),
    ]
