# Generated by Django 2.2.5 on 2019-11-18 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='squad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='showup.Squad'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='showup.Genre'),
        ),
    ]
