# Generated by Django 2.2.5 on 2019-11-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showup", "0002_auto_20191118_1537"),
        ("showup", "0003_auto_20191118_1619"),
    ]

    operations = []
