# Generated by Django 2.2.5 on 2019-11-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showup", "0004_merge_20191118_1643"),
        ("showup", "0003_auto_20191118_1915"),
    ]

    operations = []
